#!/bin/bash

unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   OPEN=xdg-open
elif [[ "$unamestr" == 'Darwin' ]]; then
   OPEN=open 
fi

for f in *.txt
do
	RES=`grep -i "$1" "$f"` 
	if [[ -n $RES ]] ; then
		FILE="${f/txt/pdf}"
		echo "$FILE"
		$OPEN "$FILE" &
	fi
done

