#!/bin/bash

unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
   OPEN=xdg-open
elif [[ "$unamestr" == 'Darwin' ]]; then
   OPEN=open 
fi

for f in `grep -iH "$1" *.txt | sed -e 's/txt:.*/pdf/' | uniq | xargs `
do
	$OPEN "$f" &
done

